services:
  memebot:
    image: ghcr.io/evd09/memebot:latest
    container_name: memebot
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./sounds:/app/sounds
      - ./logs:/app/logs
    # ports:
    #   - "3000:3000"  # Optional: if you add a web UI, etc.

